name: e_commerce_halfa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  auto_animated: ^3.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  country_icons: ^3.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.1.0
  flutter_otp_text_field: ^1.5.1+1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  get_it: ^8.0.3
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  jiffy: ^6.4.3
  path: ^1.9.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  show_up_animation: ^2.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/on_board1.svg
    - assets/images/onboarding/on_board2.svg
    - assets/images/onboarding/on_board3.svg
    - assets/images/onboarding/on_board4.svg
    - assets/images/onboarding/lang.png
    - assets/images/auth/Login-amico.svg
    - assets/images/auth/sign_up_amico.svg
    - assets/images/auth/Forgot_password.svg
    - assets/images/auth/email.svg
    - assets/images/auth/otp.svg
    - assets/images/auth/reset_passowrd.svg
    - assets/images/auth/verified.svg
    - assets/images/auth/success.svg

  fonts:

    - family: playFair
      fonts:
        - asset: assets/fonts/play_fair/PlayfairDisplay-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/play_fair/PlayfairDisplay-VariableFont_wght.ttf
    
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-VariableFont_slnt,wght.ttf
