name: e_commerce_halfa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  auto_animated: ^3.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.1.0
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_it: ^8.0.3
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  jiffy: ^6.4.3
  path: ^1.9.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  show_up_animation: ^2.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/on_board1.svg
    - assets/images/onboarding/on_board2.svg
    - assets/images/onboarding/on_board3.svg
    - assets/images/onboarding/on_board4.svg

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
