// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzk36ZzBpoUva68LoKfflDcJS5YpIgTLQ',
    appId: '1:1080261248566:android:ec28ecf39c21d117f8ba97',
    messagingSenderId: '1080261248566',
    projectId: 'e-commerce-halfa',
    storageBucket: 'e-commerce-halfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAK9sVVdvKQLXzhlx9bgxy6a2ibFNV7fU',
    appId: '1:1080261248566:ios:7417cdde423598b3f8ba97',
    messagingSenderId: '1080261248566',
    projectId: 'e-commerce-halfa',
    storageBucket: 'e-commerce-halfa.firebasestorage.app',
    androidClientId: '1080261248566-r4rl0ic5o7lnalegi1po31lcpacs4t3e.apps.googleusercontent.com',
    iosClientId: '1080261248566-mj71b73h8cs59135ec1m69n4se9cdcj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceHalfa',
  );
}
